{% set name = "Chameleon" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Chameleon-{{ version }}.tar.gz
  sha256: 4cfc1ba46a6793b8ec4c72dd324dc647a916bcf588ab0df6f6b57f33ac3a4bb7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4
  run:
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4

test:
  imports:
    - chameleon
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://chameleon.readthedocs.io
  summary: Fast HTML/XML Template Compiler.
  license: BSD-4-Clause
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ReimarBauer
