{% set name = "Chameleon" %}
{% set version = "3.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Chameleon-{{ version }}.tar.gz
  sha256: ad0ea57e1a7774b78d8c3e86f44a63a53adcfca1f2ba85911506550aedccd0fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4
  run:
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4

test:
  imports:
    - chameleon
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://chameleon.readthedocs.io
  summary: Fast HTML/XML Template Compiler.
  license: BSD-4-Clause
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ReimarBauer
